primary_region = "ams"

[deploy]
  # If the health check goes into a critical state and won't recover, switch back to "rolling" and re-deploy.
  # Then switch back to "bluegreen".
  strategy = "bluegreen"

[http_service]
  internal_port = 8888
  force_https = true

[[http_service.checks]]
  grace_period = "1m"
  interval = "15s"
  method = "GET"
  timeout = "30s"
  protocol = "http"
  path = "/"
